apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  labels:
    app: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
      - name: operator
        image: operator:1.0
        imagePullPolicy: IfNotPresent
        tty: true
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: operator
  labels:
    app: operator
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: operator
